FROM node:lts-alpine

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

RUN npm i -g pnpm

WORKDIR /home/node/app
RUN mkdir -p /home/node/app

COPY package*.json ./
RUN pnpm install

COPY . .
RUN pnpm build

RUN chown -R node:node /home/node/app
USER node

CMD ["pnpm", "preview", "--host", "0.0.0.0", "--port", "3000"]

EXPOSE 3000
