---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: vite-app
  namespace: vite-app
spec:
  image: ghcr.io/gmarcha/vite-app
  interval: 5m
  secretRef:
    name: ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: vite-app
  namespace: vite-app
spec:
  imageRepositoryRef:
    name: vite-app
    namespace: vite-app
  policy:
    semver:
      range: '>0.0.0 <1.0.0'
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vite-app
  namespace: vite-app
spec:
  interval: 5m0s
  url: https://github.com/gmarcha/vite-app
  ref:
    branch: master
  secretRef:
    name: ghr
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: vite-app
  namespace: vite-app
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: vite-app
    namespace: vite-app
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: gmarcha@github.com
        name: gmarcha
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    strategy: Setters
    path: ./deploy/app
