apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: vite-app
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vite-app
  namespace: vite-app
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: vite-app-https-redirect@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: gamarcha.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: vite-app
            port:
              name: http
  tls:
  - secretName: gamarcha.com-tls
    hosts:
    - gamarcha.com
