apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: ghcr.io/gmarcha/vite-app:0.2.1 # {"$imagepolicy": "flux-system:vite-app"}
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
      imagePullSecrets:
      - name: ghcr
